modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "LGPLv3"


[[mods]]
modId = "immersive_weathering"
version = "${version}"
displayName = "Immersive Weathering"
authors = "Ordana, MehVahdJukaar, Keybounce"

logoFile="icon.png" #optional
description = '''
An abundance of new natural systems to make your world feel more alive than ever.
'''
#logoFile = ""

[[dependencies.immersive_weathering]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_weathering]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.immersive_weathering]]
modId = "moonlight"
mandatory = true
versionRange = "[1.20-2.7.0,]"
ordering = "NONE"
side = "BOTH"

